---
title: "Adult Depression in California through 2012 to 2018"
author: Ashas Memon
thanks: "Code and data are available at: https://github.com/ashasmemon/MentalHealthExploration"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "This report aims to examine Adult Depression in California as an indicator in Lets’ Get Healthy California including a general breakdown of age, sex, ethnicity and education. It discusses data collection methodology and examines the changes in depression rates among adults from various backgrounds ands education levels from 2012 to 2018. The data examines here was collected by asking, “Has a doctor, nurse or other health care professional ever told you that you have depressive disorder?”"
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE, show_col_types = FALSE}

# install.packages("haven")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("janitor")
# install.packages("tidyr")
# install.packages("ggplot2")
# install.packages("lubridate")
# install.packages("gridExtra")
# install.packages("scales")
# install.packages("knitr")
library(haven)
library(tidyverse)
library(dplyr)
library(janitor) # Helps clean datasets
library(tidyr) # Helps make tidy datasets
library(ggplot2)
library(lubridate)
library(gridExtra)
library(scales)
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Over the past 3 years with the economic recession due to the Covid-19 pandemic, there has been an increase in the number of people affected by some type of mental health disorder. As the pandemic progressed, there has been a significant increases in reported cases of individuals and households with anxiety or depressive disorder mostly attributed to the prolonged public health measures (https://www.kff.org/coronavirus-covid-19/issue-brief/the-implications-of-covid-19-for-mental-health-and-substance-use/ ).  The data was collected as an indicator in Lets’ Get Healthy California and includes a general breakdown of age, sex, ethnicity, education (among other strata) of individuals who reported they had a depressive disorder. The data was collected as part of an annual health related telephone survey conducted for California Behavioral Risk Factor Surveillance Survey (BRFSS), where individuals were asked, “Has a doctor, nurse or other health care professional EVER told you that you have a depressive disorder (including depression, major depression, dysthymia or minor depression)?”. The frequencies of all these individuals who responded to this was recorded in multiple tables. It is important to note that this particular dataset is not affiliated with the Centre for Disease Control and Prevention (CDC) or any other federal agencies, it is a stand-alone set and only contains data from 2012 up to 2018.

# Data


## Data Summary


## R Packages

# Methodology

## Features

## Sampling Population 

## Sampling Method

## Strengths

## Weaknesses

## Question Discussion 

# Findings 
 Talk about 3-4 aspects in this paper 
 
# Discussion Based on Findings 

# Privacy and Ethics 

# Appendix

# Reference
